### PR TITLE
removes null safety operator no longer needed

### PR DESCRIPTION
**Pull request by tek08**

### CODE REVIEW

**Comment by tek08** [comment]
Fixes #6

**Comment by tetianazakhozhaeva** [comment]
merge it plz

**Comment by tetianazakhozhaeva** [comment]
waiting for project update

**Comment by tek08** [comment]
I don't have permissions to do so without original repo owner giving the ok. For now, you can supply an override in your pubspec that refers to this commit.

**Comment by tetianazakhozhaeva** [comment]
@victorevox merge it plz

**Comment by tetianazakhozhaeva** [comment]
> I don't have permissions to do so without original repo owner giving the ok. For now, you can supply an override in your pubspec that refers to this commit.

@tek08 Thanks

**Comment by victorevox** [comment]
Thanks @tek08 !

**Pull request merged**
